name: Joeboy DotNet CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  dev:
    name: Run Dotnet Build and Test
    uses: ./.github/workflows/reusable-workflow.yml

    
